#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Starts tmux if the current session isn't tmux already
# Source: https://stackoverflow.com/a/51922746
if [ command -v tmux >/dev/null 2>&1 ]; then
    if [ -t 0 ] && [[ -z $TMUX ]] && [[ $- = *i* ]]; then exec tmux; fi
fi
