#!/bin/bash

# ls
alias l="ls"
alias la="ls -A"
alias ll="ls -hl"
alias lla="ls -hlA"

if [[ $OS == "Windows" ]]; then
  alias lh="ls -d .?*"
  alias llh="ls -ld .?*"
else
  alias lh="ls -d .!(|.)"
  alias llh="ls -hld .!(|.)"
fi

# vim
alias vim="nvim"
alias vi="vim"

# python
alias ipy="ipython"
alias py="python"
alias pye="pyenv"
alias venv="python -m venv"
alias pe="pyenv"
alias pv="pyenv venv"

# lua
alias lua="lua.exe"
alias luarocks="lua \"$LUA_DEV/luarocks.lua\""

# other
alias qmake="qmake-qt5"
alias lg="lazygit"
