#!/bin/bash

if [[ $OS == "Windows" ]]; then
  # NeoVim
  config_nvim=~/AppData/Local/nvim
  # Windows Terminal
  config_windows_terminal=~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/
  # Bash
  config_bash=~
else
  # NeoVim
  config_nvim=~/.config/nvim
  # Bash
  config_bash=~
fi
