#!/bin/bash

# Synth Shell Imports
#
##-----------------------------------------------------
## synth-shell-prompt.sh
if [ -f /home/wolf/.config/synth-shell/synth-shell-prompt.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source /home/wolf/.config/synth-shell/synth-shell-prompt.sh
fi

##-----------------------------------------------------
## better-ls
if [ -f /home/wolf/.config/synth-shell/better-ls.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source /home/wolf/.config/synth-shell/better-ls.sh
fi

##-----------------------------------------------------
## alias
if [ -f /home/wolf/.config/synth-shell/alias.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source /home/wolf/.config/synth-shell/alias.sh
fi

##-----------------------------------------------------
## better-history
if [ -f /home/wolf/.config/synth-shell/better-history.sh ] && [ -n "$( echo $- | grep i )" ]; then
	source /home/wolf/.config/synth-shell/better-history.sh
fi

